select = [
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "PERF", # perflint
    "PL",   # pylint
    "UP",   # pyupgrade
]

ignore = ["PERF203"]


[per-file-ignores]
"__init__.py" = ["F401"]
"**/migrations/*.py" = ["N806"]
"nginx/**" = []


[pylint]
max-args = 7
