# Generated by Django 5.0.2 on 2024-06-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived", models.DateTimeField(blank=True, editable=False, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("contact", models.TextField()),
            ],
            options={
                "ordering": ["-last_updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived", models.DateTimeField(blank=True, editable=False, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("suppliers", models.ManyToManyField(related_name="items", to="inventory.supplier")),
            ],
            options={
                "ordering": ["-last_updated"],
                "abstract": False,
            },
        ),
    ]
