name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pipeline
  push:
    branches:
      - master


jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Stop Lint if pull request is closed
        if: github.event.action == 'closed'
        run: |
          echo "The deployment failed because it was a closed event."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip curl
          pip3 install -r lint_req.txt

      - name: Lint code
        run: |
          black . --exclude="venv/*" --line-length 119 --preview
          ruff check .